### ISSUE TITLE
Updating database

### ISSUE THREAD

**Issue by SalemDr** [psauthor/CoreApiFundamentals#11]
I downloaded the 5.0 code version. I cd to the directory in the terminal to update the database. however, I keep getting the following:
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-ef does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

**Comment by SalemDr** [comment]
**Okay, i installed dotnet ef, i did not have it in the first place. however, a new error at the Build occurred. 2 errors were shown as follows:**
C:\Program Files\dotnet\sdk\5.0.402\Microsoft.Common.CurrentVersion.targets(4502,5): error MSB3027: Could not copy "obj\Debug\net5.0\CoreCodeCamp.dll" to "bin\Debug\net5.0\CoreCodeCamp.dll". Exceeded retry count of 10. Failed.  [C:\Users\Dr. Salem\Desktop\CoreApiFundamentals-5.0\src\CoreCodeCamp.csproj]
C:\Program Files\dotnet\sdk\5.0.402\Microsoft.Common.CurrentVersion.targets(4502,5): error MSB3021: Unable to copy file "obj\Debug\net5.0\CoreCodeCamp.dll" to "bin\Debug\net5.0\CoreCodeCamp.dll". The process cannot access the file 'C:\Users\Dr. Salem\Desktop\CoreApiFundamentals-5.0\src\bin\Debug\net5.0\CoreCodeCamp.dll' because it is being used by another process. [C:\Users\Dr. Salem\Desktop\CoreApiFundamentals-5.0\src\CoreCodeCamp.csproj]

**Comment by shawnwildermuth** [comment]
You were still running the project, you need to stop that process. Please ask these questions in the future on the Course Discussion tab. I can't answer them here.
