### ISSUE TITLE
AutoMapper Issue after adding ICollection

### ISSUE THREAD

**Issue by SvenUweSchubert** [psauthor/CoreApiFundamentals#9]
Hi,

I run in a error if I try to call the api with the **includeTasks = true** (http://localhost:6600/api/camps?includeTalks=true).

This is the error message:

    > Error mapping types.
    > 
    > Mapping types:
    > Object -> CampModel[]
    > System.Object -> CoreCodeCamp.Models.CampModel[]

I am using .net Core 5. 

Do you have any hint for me in order to fix this. 

Thanks Sven

**Comment by shawnwildermuth** [comment]
Can you ask this on the course "Discussion" tab?
